# Generated by Django 4.0.3 on 2022-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt_app', '0002_clients_services_delete_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
    ]
