# Generated by Django 4.0.3 on 2022-04-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvt_app', '0003_stuff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Staff',
        ),
    ]
